"use client";
import Header from "@/components/layout/Header/Header";
import "./globals.scss";
import Footer from "@/components/layout/Footer/Footer";
import { CategoriesProvider } from "@/context/CategoriesProvider";
import FAQ from "@/components/layout/FAQ/FAQ";
import Script from "next/script";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="robots" content="noindex,nofollow" />
      </head>
      <body>
        <Script
          type="text/javascript"
          id="yandex-metrika"
          strategy="afterInteractive"
        >
          {` (function(m,e,t,r,i,k,a){
        m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();
        for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
        k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
    })(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=105445789', 'ym');
    ym(105445789, 'init', {ssr:true, webvisor:true, trackHash:true, clickmap:true, ecommerce:"dataLayer", accurateTrackBounce:true, trackLinks:true});`}
        </Script>
        <CategoriesProvider>
          <Header />
          <main className="container">{children}</main>
          <FAQ />
          <Footer />
        </CategoriesProvider>
      </body>
    </html>
  );
}
